import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "swiper/css";
import "swiper/css/effect-fade";
import "./bootstrap.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "@/components/navbar/Header";
import "@/public/css/fonts.css";
import "animate.css";
import "./globals.css";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/scrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome To Essensial Oil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div >
          <Header />
          {children}
          <Footer/>
        </div>
       <ScrollToTop/>
      </body>
    </html>
  );
}
